title: her.sh
url: http://her.sh
blog: http://list.her.sh

sandbox:
  url: https://z.her.sh

splinesoft: 
  url: http://splinesoft.net
  github: https://github.com/splinesoft

mudurl: https://itunes.apple.com/us/app/mudrammer-a-modern-mud-client/id597157072?mt=8
bequesturl: https://github.com/splinesoft/bequest
ciurl: https://circleci.com/gh/jhersh/her.sh

exclude: [gems, Gemfile, Gemfile.lock, readme.md, Rakefile, vendor]

author:
  name: Jonathan Hersh
  email: jon@her.sh
  twitter: https://twitter.com/jhersh
  adn: https://alpha.app.net/jhersh
  github: https://github.com/jhersh
  linkedin: https://www.linkedin.com/in/jhersh
  pgp: http://her.sh/pgp.txt
  source: https://github.com/jhersh/her.sh
  keybase: https://keybase.io/zz
